<?xml version="1.0" encoding="utf-8"?><Database Name="gramman" Class="SampleTableDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=gramman;Integrated Security=True" SettingsObjectName="LINQtoSQL.Properties.Settings" SettingsPropertyName="grammanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SampleTable" Member="SampleTable">
    <Type Name="SampleTable">
      <Column Name="id" Type="System.Int32" DbType="Int" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="birthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>